Vulphair
ss220club/Paradise-Remake pull request #120
Opened 2023-08-01 20:57 UTC by OricyUwU

## Что этот PR делает
Пачка новых волос для расы Vulpkanin.
Мужские и женские варианты, честно позаимствованы и адаптированы под расу.

## Почему это хорошо для игры
Причёски круто

## Изображения изменений

Нет таких
## Тестирование

Не тестировал
## Changelog
Gatto

2023-08-01 20:57 UTC, Aylong220 commented
>Тестирование - Не тестировал
Based

2023-08-01 21:34 UTC, Furrior commented
Зачем у всех путей причесок есть vulp_ в начале, если там и так ясно, что они для вульп?

2023-08-01 21:34 UTC, Aylong220 commented
> Зачем у всех путей причесок есть vulp_ в начале, если там и так ясно, что они для вульп?

Копипаст я так понял

2023-08-01 21:35 UTC, Furrior requested changes

2023-08-01 21:35 UTC, Furrior commented on modular_ss220/hairs/_hairs.dm
> +	name = "Новые волосы "
Лишний пробел

2023-08-01 21:35 UTC, Furrior commented on modular_ss220/hairs/code/vulpkanin_hair.dm
> +	icon = 'modular_ss220/hairs/icons/vulpkanin_hair.dmi'
А если оффы добавят новые прически? Иди прописывай каждой своей иконку, а отсюда убери

2023-08-01 21:40 UTC, OricyUwU commented on modular_ss220/hairs/code/vulpkanin_hair.dm
> +	icon = 'modular_ss220/hairs/icons/vulpkanin_hair.dmi'
Убрать вообще убрать или тут должна быть ссылка на оригинальный файл?

2023-08-01 21:40 UTC, Furrior commented
А еще тесты упали

2023-08-01 21:41 UTC, Furrior commented on modular_ss220/hairs/code/vulpkanin_hair.dm
> +	icon = 'modular_ss220/hairs/icons/vulpkanin_hair.dmi'
Вообще убери эти 3 строки

2023-08-02 02:20 UTC, Furrior commented on modular_ss220/hairs/code/vulpkanin_hair.dm
> +	icon = 'modular_ss220/hairs/icons/vulpkanin_hair.dmi'
А прописать всем добавленным иконку?

2023-08-02 04:46 UTC, OricyUwU commented on modular_ss220/hairs/code/vulpkanin_hair.dm
> +	icon = 'modular_ss220/hairs/icons/vulpkanin_hair.dmi'
Готово

2023-08-03 18:14 UTC, Furrior commented on modular_ss220/hairs/_hairs.dme
> +#include "_hairs.dm"
Пусть первым идет

2023-08-03 18:24 UTC, OricyUwU commented
> Зачем у всех путей причесок есть vulp_ в начале, если там и так ясно, что они для вульп?

Потому что они для вульп XyliPizdish

2023-08-06 21:33 UTC, Furrior commented
Так же, вижу дубликату уже существующих причесок, непонятно зачем. Не вижу, что бы спрайт отличался у них

2023-08-11 17:03 UTC, Furrior approved these changes

2023-08-11 17:04 UTC, merged