SpaceRuin: Remap old WildWest
ss220club/Paradise-Remake pull request #143
Opened 2023-08-20 22:19 UTC by konushi

## Что этот PR делает
Ремап WildWest для гейта, теперь это косморуина. 
Добавлено: новая карта, неразрушаемые стены (культ, камень), новые звуки в spookoween, новые зоны
Лут: шахтариги (если их кто-то снимает), КА, 2 бладрига, 2 црки (падают с симплов в мусорке и у печей), пара вещей культа, wishgranter_super 

## Почему это хорошо для игры
Больше косморуин - больше косморуин

## Изображения изменений

![2023-08-18 17 11 43](https://github.com/ss220club/Paradise-Remake/assets/139562134/f2d2228e-ab47-4757-9ff3-ae4a5f9c52cb)

## Тестирование

Вроде работает
Эмоспрайты - триггеры и гибсы

## Changelog

:cl:
add: Новую косморуину - space_wildwest, неразрушаемые стены (культ, камень), новые звуки в spookoween, новые зоны
soundadd: spookoween - scary_whisper1,2; many_whisper1,2; low_laugh
/:cl:

2023-08-21 12:24 UTC, Aylong220 requested changes
Код в модули

2023-08-21 12:24 UTC, Aylong220 commented on code/game/area/ss13_areas.dm
> +/area/awaymission/wwspace
В модуль. Создай в папке 'modular_ss220\_maps220\code' папку Areas, в ней файл away.dm и в него уже свои зоны.
Не забудь добавить away.dm в _maps220.dme

2023-08-21 12:24 UTC, Aylong220 commented on code/game/turfs/simulated/walls_indestructible.dm
> +/turf/simulated/wall/indestructible/rock/mineral
Стены так же в модуль modular_ss220\aesthetics\walls\code\walls.dm'

2023-08-21 12:25 UTC, Aylong220 commented on sound/spookoween/scary_whisper2.ogg
Звуки тоже в модуль, думаю в 'modular_ss220\aesthetics_sounds' будет неплохо

2023-08-21 12:31 UTC, Aylong220 commented on code/game/area/ss13_areas.dm
> +    dynamic_lighting = DYNAMIC_LIGHTING_FORCED
requires_power = FALSE
dynamic_lighting = DYNAMIC_LIGHTING_FORCED
Не обязательно вписывать везде, если не надо значение отличающееся от родителя /area/awaymission/wwspace

Просто пропиши это всё в нём и удали у "детей"

2023-08-21 12:33 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-Remake/assets/69762909/15c53b2b-9d34-42eb-beeb-694a50faf646)
Местами на песочек забыл зону поставить

2023-08-21 12:34 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-Remake/assets/69762909/1b43f07d-f65d-4a22-a7c6-7a8a89e1bf27)
Как кстати эти двери открываются?

2023-08-21 12:36 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-Remake/assets/69762909/38b23851-01c3-4a9f-9c16-90cae21858ce)
2450 кредитов, это очень много

2023-08-21 19:48 UTC, Aylong220 requested changes

2023-08-21 19:48 UTC, Aylong220 commented on modular_ss220/_maps220/_maps220.dme
> +// BEGIN_INTERNALS
Подчисти файлик

2023-08-21 19:48 UTC, Aylong220 commented on code/game/area/ss13_areas.dm
> -
Верни строчку XtliPizdish

2023-08-21 19:48 UTC, Aylong220 commented on modular_ss220/_maps220/code/RandomRuins/space_ruins.dm
> +    always_place = FALSE
Нет пустой строчки после кода

2023-08-21 21:25 UTC, Aylong220 approved these changes
Вроде всё найс

2023-08-25 18:38 UTC, Furrior commented
Пробелы вместо табов, судя по тестам

2023-08-26 13:22 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-Remake/assets/69762909/7c03327a-7a92-4b1b-87b8-946203b8269b)

2023-08-28 14:39 UTC, Furrior approved these changes

2023-08-28 14:40 UTC, Furrior requested changes

2023-08-28 14:40 UTC, Furrior commented on modular_ss220/aesthetics/walls/code/walls.dm
> +/turf/simulated/wall/indestructible/rock/mineral
Это не аестетика же, а совершенно новые стены

2023-08-28 14:48 UTC, merged