SpaceRuin: Remap old mechtransport
ss220club/Paradise-Remake pull request #144
Opened 2023-08-20 22:59 UTC by konushi

## Что этот PR делает
Ремап старой косморуины: mechtransport
Добавлено: новая карта, зоны, неразрушаемые стены (титановые, пластитановые), новые симплмобы (skyrat icons)
Лут: ресурсы, инструменты, части мехов, старый дюранд

## Почему это хорошо для игры
Больше косморуин - больше косморуин

## Изображения изменений

![image](https://github.com/ss220club/Paradise-Remake/assets/139562134/b4b48005-c4b9-4eeb-9de0-8fc98145331b)

## Тестирование

Вроде работает
## Changelog

:cl:
add: новая косморуина - mechtransport_new, зоны, неразрушаемые стены (титановые, пластитановые), новые симплмобы
imageadd: новые симплмобы (skyrat icons)
/:cl:

2023-08-21 12:38 UTC, Aylong220 commented
Всё так же в модуль

2023-08-22 09:56 UTC, Aylong220 requested changes

2023-08-22 09:56 UTC, Aylong220 commented on code/game/turfs/simulated/walls_indestructible.dm
> +
2 лишние строчки

2023-08-28 14:39 UTC, Aylong220 commented
Линтер плачет, там миссклик в одном тайле

2023-08-28 15:12 UTC, Aylong220 requested changes
NearStation на то что выходит за рамки руины и находится в космосе
![image](https://github.com/ss220club/Paradise-Remake/assets/69762909/5d23def5-53d8-4772-b014-dfbdb6d46011)

Кхм, что за...
Так не делай...
Поставь обычные machine frame везде.
И больше так пожалуйста не делай
![image](https://github.com/ss220club/Paradise-Remake/assets/69762909/618cabf1-e8c1-47a1-b5d5-628162ca5237)

В остальном вроде порядок

2023-08-29 12:56 UTC, Aylong220 approved these changes
Пойдёт

2023-08-29 19:41 UTC, Furrior approved these changes

2023-08-29 19:41 UTC, merged