[FEAT] Aesthetics
ss220club/Paradise-Remake pull request #24
Opened 2023-07-16 12:32 UTC by larentoun

## Что этот PR делает

Изменяет иконки

## Почему это хорошо для игры

Свой любимый франкенштейн

## Изображения изменений

icondiff time

## Тестирование

рано

## Changelog

:cl:
add: New icons
/:cl:

2023-07-16 15:57 UTC, larentoun commented
Двери и стены будут позже, это пока можно заливать

2023-07-16 19:54 UTC, Furrior requested changes
Не выглядит завершенным

2023-07-16 19:54 UTC, Furrior commented on code/game/objects/items/weapons/storage/secure.dm
> -		overlays += image('icons/obj/storage.dmi', icon_sparking)
А че просто icon не заменить?

2023-07-16 19:54 UTC, Furrior commented on modular_ss220/aesthetics/boxes/code/boxes.dm
> +	icon = 'modular_ss220/aesthetics/boxes/icons/boxes.dmi'
Почему где то указан айконстейт, а где то нет?

2023-07-16 19:54 UTC, Furrior commented on modular_ss220/aesthetics/briefcases/code/briefcases.dm
> +	icon = 'modular_ss220/aesthetics/briefcases/icons/briefcases.dmi'
Вот тут не указан, например

2023-07-16 19:54 UTC, Furrior commented on modular_ss220/aesthetics/piano/code/piano.dm
> +/obj/structure/musician/piano
И что это?

2023-07-16 19:54 UTC, Furrior commented on modular_ss220/aesthetics/racks/code/racks.dm
> +/obj/structure/rack/gunrack/attackby(obj/item/W, mob/user, params) //TODO: fix logic
Прикольное туду

2023-07-16 19:54 UTC, Furrior commented on modular_ss220/aesthetics/soap/code/soap.dm
> +/obj/item/soap
пепелист

2023-07-17 09:17 UTC, larentoun commented on code/game/objects/items/weapons/storage/secure.dm
> -		overlays += image('icons/obj/storage.dmi', icon_sparking)
Я это на офф запихну, как они освободятся

2023-07-17 09:18 UTC, larentoun commented on modular_ss220/aesthetics/boxes/code/boxes.dm
> +	icon = 'modular_ss220/aesthetics/boxes/icons/boxes.dmi'
Потому что используется тот же, что и в файле

2023-07-17 09:18 UTC, larentoun commented on modular_ss220/aesthetics/briefcases/code/briefcases.dm
> +	icon = 'modular_ss220/aesthetics/briefcases/icons/briefcases.dmi'
Потому что используется тот же, что и в файле

2023-07-17 09:19 UTC, larentoun commented on modular_ss220/aesthetics/piano/code/piano.dm
> +/obj/structure/musician/piano
Это нужно спросить @Ayling220 , что за пиано это должно быть

2023-07-17 09:19 UTC, larentoun commented on modular_ss220/aesthetics/racks/code/racks.dm
> +/obj/structure/rack/gunrack/attackby(obj/item/W, mob/user, params) //TODO: fix logic
Это тоже нужно переводить на оффы, как они освободятся

2023-07-17 09:19 UTC, larentoun commented on modular_ss220/aesthetics/soap/code/soap.dm
> +/obj/item/soap
Куча мыл, которых нет на оффах. Не знаю, зачем их мне дали, пока пусть лежит, как разберемся

2023-07-17 15:18 UTC, Furrior commented on modular_ss220/modular_ss220.dme
> +// END_PREFERENCES
А куча комментов этих зачем?

2023-07-17 15:33 UTC, larentoun commented on modular_ss220/modular_ss220.dme
> +// END_PREFERENCES
Оппа, а это я забыл убрать после запуска через ДМ

2023-07-17 15:35 UTC, larentoun commented on modular_ss220/modular_ss220.dme
> +// END_PREFERENCES
Готово

2023-07-19 04:11 UTC, Furrior approved these changes

2023-07-19 04:12 UTC, merged