[FEAT] unique objects from SS220
ss220club/Paradise-Remake pull request #33
Opened 2023-07-19 17:22 UTC by PhantornRU

## Что этот PR делает
Портируем статуи, предметы, сортиры.
Добавляем возможность собрать эти сортиры.

## Почему это хорошо для игры
В будущем будет пополняться и дальше тем что не допортировали

## Изображения изменений

## Тестирование
Работает во.

## Changelog
:cl:
add: unique objects from SS220
/:cl:

/:cl:

2023-07-19 17:29 UTC, larentoun commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	desc = "Загадочная девушка, ныне одна из множества офицеров синдиката. Получившая столь высокую позицию не за связи, а за свои способности. \
Кринжанул с этого описания

2023-07-19 17:32 UTC, PhantornRU commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	desc = "Загадочная девушка, ныне одна из множества офицеров синдиката. Получившая столь высокую позицию не за связи, а за свои способности. \
В начале оригинальное описание, в конце уже добавлено от меня. Если есть что добавить - можешь внести изменения. xdd

2023-07-19 17:36 UTC, larentoun requested changes

2023-07-19 17:36 UTC, larentoun commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	desc = "Бедный Йорик..."
А тут не должно быть иконки? Или это просто описание измененое для черепа?

2023-07-19 17:36 UTC, larentoun commented on modular_ss220/unique_objects/code/unique_objects.dm
> +		visible_message("Недостаточно материала, нужно хотя бы [need_amount] шт.")
А зачем это, а не `to_chat()`?

2023-07-19 17:36 UTC, larentoun commented on modular_ss220/unique_objects/code/unique_objects.dm
> +			visible_message("Неподходящая цель для гравировки.")
Тоже самое, `to_chat()`

2023-07-19 17:36 UTC, larentoun commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	if(do_after(user, 20, target = src))
```suggestion
	if(do_after(user, 2 SECONDS, target = src))
```

2023-07-19 17:36 UTC, larentoun commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	icon_state = "gold_toilet[open][cistern]-NT"
Если меняется только стейт, то перезаписать стоит `update_icon_state()`

2023-07-19 17:36 UTC, larentoun commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	. = ..()
Тоже самое, `update_icon_state()`

2023-07-19 17:36 UTC, larentoun commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	icon_state = "bluespace_toilet[open][cistern]-NT"
`update_icon_state()`

2023-07-19 17:36 UTC, larentoun commented on modular_ss220/unique_objects/code/cheese_statue.dm
> +	return ..()
Мб стоит перенести логику в `update_icon_state()`, а тут как раз вызывать `update_icon(UPDATE_ICON_STATE)`

2023-07-20 05:34 UTC, PhantornRU commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	desc = "Бедный Йорик..."
Неа, не должно быть. Это чисто объект в офис магистрата как на старопаре чтобы заменить старый именной череп.

2023-07-20 07:52 UTC, Furrior requested changes

2023-07-20 07:52 UTC, Furrior commented on modular_ss220/unique_objects/code/cheese_statue.dm
> +	if(obj_integrity <= 65)
Яндередев, плюс верхние варианты никогда не сработают

2023-07-20 07:52 UTC, Furrior commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	emagged = FALSE
Зачем? Не поверю, что в родителе емаггед уже тру

2023-07-21 07:53 UTC, PhantornRU commented
@Furrior сырная статуя теперь нормально работает. Емаггед выпилен.
Капитан теперь может устроить сортирный культ.
![image](https://github.com/ss220club/Paradise-Remake/assets/41479614/954cd4ef-f6aa-4a1a-8625-9aa6f9d6791e)

2023-07-23 22:00 UTC, Furrior requested changes

2023-07-23 22:00 UTC, Furrior commented on modular_ss220/unique_objects/code/unique_objects.dm
> +/obj/structure/toilet/proc/construct(var/obj/item/stack/M, mob/living/user, var/build_type, var/amount)
Убери var/

2023-07-23 22:00 UTC, Furrior commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		/obj/item/stack/sheet/cheese = list("milk" = 20),
В модуль

2023-07-23 22:00 UTC, Furrior commented on code/game/objects/structures/watercloset.dm
> +	if(try_construct(I, user))
В модуль

2023-07-24 01:27 UTC, Furrior commented
Еще чейнджлог сомнительный

2023-07-24 07:13 UTC, PhantornRU commented
@Furrior всё-таки запихнул в модуль. Оказывается так проки дозаписывать можно, я думал иначе.
VAR'ы убрал, чейнджлог поправил

2023-07-24 12:37 UTC, Furrior requested changes

2023-07-24 12:37 UTC, Furrior commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	desc = "Загадочный клоун с жёлтым оттенком кожи и выразительными зелёными глазами. Лучший двойной агент синдиката умудрявшийся захватить власть множества объектов. \
"захватить власть множества объектов" - звучит как хуйня

2023-07-24 12:37 UTC, Furrior commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	desc = "Информация на табличке под статуей исцарапана и нечитабельна... Поверх написана невнятная вселенская смесь из слов \"Furry\" и \"Universe\""
"вселенская смесь" - тоже звучит так себе

2023-07-24 12:37 UTC, Furrior commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	desc = "Капитан всех уточек на этой станции. Крайне важная и престижная уточка. Выпущены в ограниченных экземплярах и только для капитанов. Ценная находка для коллекционеров."
не экземплярах, а тираже

2023-07-24 12:37 UTC, Furrior commented on modular_ss220/unique_objects/code/unique_objects.dm
> +		to_chat(user, "<span class='warning'>Этот унитаз достиг пика своего великолепия и безвкусия. Нельзя больше улучшить.</span>")
своего безвкусия? Может убрать своего?

2023-07-24 16:03 UTC, PhantornRU commented on modular_ss220/unique_objects/code/unique_objects.dm
> +	desc = "Загадочный клоун с жёлтым оттенком кожи и выразительными зелёными глазами. Лучший двойной агент синдиката умудрявшийся захватить власть множества объектов. \
оригинальный портированный текст. Ладно, ща че-нить придумаем.

2023-07-24 20:59 UTC, Furrior commented
Судя по тестам, вар в аргументах прока все еще есть

2023-07-25 00:52 UTC, PhantornRU commented
> Судя по тестам, вар в аргументах прока все еще есть

Да, 1 пропустил. Убрал.

2023-07-25 10:36 UTC, Furrior approved these changes

2023-07-25 10:37 UTC, merged